### PR TITLE
Add INLA FAQ page

### LINKED ISSUE #115: Add in the FAQ page
Add the FAQ page for INLA failures, @XueqingYin  to review current work.

### PR DESCRIPTION
**Pull request by gareth-j**
* **Summary of changes** (Bug fix, feature, docs update, ...)

Adds INLA FAQ page

* **Please check if the PR fulfills these requirements**

- [x] Closes #115 
- [x] Vignettes updated/added
- [x] Added an entry in the latest `CHANGELOG.md` file if fixing a bug or adding a new feature

### CODE REVIEW

**Review by XueqingYin — CHANGES_REQUESTED** [review]
Thanks @gareth-j and @mnky9800n. In section # Are you running the model in verbose mode?#, I suggest removing the options "inla.mode="classic", # or “inla.mode="experimental" as this part is only related to running the model in verbose mode. Apart from that, all is good.

**Comment by mnky9800n** [comment]
> Thanks @gareth-j and @mnky9800n. In section # Are you running the model in verbose mode?#, I suggest removing the options "inla.mode="classic", # or “inla.mode="experimental" as this part is only related to running the model in verbose mode. Apart from that, all is good.
> 
> Xueqing

this confuses me because i have gotten model to run by simply changing from `experimental` to `classic`. is this true? it only governs the verbose mode?

**Review by XueqingYin — APPROVED** [review]
It looks good now.

**Comment by mnky9800n** [comment]
@gareth-j can you check the pkgdown requirement

**Pull request merged**
