### PR TITLE
Update plot_mapping.R

### LINKED ISSUE #306: hydro tutorial doesn't plot shape file for catchment
it downloads the data but it doesn't plot the catchment

image

### PR DESCRIPTION
**Pull request by aabelean**
Fixed the issue of map not appearing and added options in line with those offered by `mapview`.

* **Summary of changes** (Bug fix, feature, docs update, ...)

* **Please check if the PR fulfills these requirements**

- [ ] Closes #306
- [ ] Tests added and passed
- [ ] All code checks passing - `styler` run over code
- [ ] Added an entry in the latest `CHANGELOG.md` file if fixing a bug or adding a new feature

### CODE REVIEW

**Comment by mnky9800n** [comment]
i believe this fails because of the geophysics tutorial

https://stackoverflow.com/questions/77530214/error-dsparsemodelmatrix-object-superclass-xmatrix-not-defined

**Comment by aabelean** [comment]
> i believe this fails because of the geophysics tutorial
> 
> https://stackoverflow.com/questions/77530214/error-dsparsemodelmatrix-object-superclass-xmatrix-not-defined

Yes, I believe so

**Comment by mnky9800n** [comment]
actually i don't see why this should be a problem, the imports here are no different than any other tutorial.

**Comment by aabelean** [comment]
> actually i don't see why this should be a problem, the imports here are no different than any other tutorial.

Looks like it cannot find `devtools` now

**Comment by aabelean** [comment]
> > actually i don't see why this should be a problem, the imports here are no different than any other tutorial.
> 
> Looks like it cannot find `devtools` now

Oh, we don't have `devtools` among imports in `DESCRIPTION`

**Pull request merged**
