### PR TITLE
Add calving tutorial notebook from 4DModeller workshop

### PR DESCRIPTION
**Pull request by icetianli**
* **Summary of changes** (Bug fix, feature, docs update, ...)

* **Please check if the PR fulfills these requirements**

- [ ] Closes #xxxx (replace xxxx with the GitHub issue number)
- [ ] Tests added and passed
- [ ] All code checks passing - `styler` run over code
- [ ] Vignettes updated/added
- [ ] Added an entry in the latest `CHANGELOG.md` file if fixing a bug or adding a new feature
- [ ] Any new libraries added to `DESCRIPTION`

### CODE REVIEW

**Comment by gareth-j** [comment]
@icetianli would you be able to share some of the data you used for this tutorial?

**Comment by icetianli** [comment]
Yeah sure, will do.

**Comment by mnky9800n** [comment]
I <THINK> that the reason this is failing is becuase it is using `ubuntu-latest` but the latest distro of ubuntu on github is not having all the R dependencies as part of the image. i could be wrong.

**Comment by mnky9800n** [comment]
i still dont know why pkgdown fails. maybe @gareth-j knows.

**Comment by mnky9800n** [comment]
```
Error: Error: processing vignette 'covid_mcmc.Rmd' failed with diagnostics:
parse error: premature EOF
```
i think there is something wrwong with the data download, but it does this for literally all of the tutorials.

**Comment by gareth-j** [comment]
@icetianli can you change the header on the tutorial vignette to match the format of the other vignettes?
It'd be something like this:

```
---
title: "Simple Linear Regression with fdmr"
output: 
  bookdown::html_document2:
    base_format: rmarkdown::html_vignette
    fig_caption: yes
bibliography: "references.bib"
link-citations: yes
vignette: >
  %\VignetteIndexEntry{Simple Linear Regression with fdmr}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```

**Comment by aabelean** [comment]
`DESCRIPTION` does not have `tidyverse` as an import, does it?

**Comment by aabelean** [comment]
The pkgdown and ubuntu errors look similar to [this StackOverflow question](https://stackoverflow.com/questions/77530214/error-dsparsemodelmatrix-object-superclass-xmatrix-not-defined). The OP was also using Ubuntu.

**Comment by mnky9800n** [comment]
> The pkgdown and ubuntu errors look similar to [this StackOverflow question](https://stackoverflow.com/questions/77530214/error-dsparsemodelmatrix-object-superclass-xmatrix-not-defined). The OP was also using Ubuntu.

Perhaps we have to have the xmatrix import in a different order?

**Comment by mnky9800n** [comment]
@icetianli i cloned your repo and tried to run your tutorial and it fails when it tries to use the formula because `fc` is not declared.

image

I am guessing you are trying to use  the data column `FrontChange` so when i replace `fc` with `FrontChange` I get this error:

image

tbh, i'm not sure what the `id.loc0` variable is doing? it also is not declared. if you remove it, you can get `inla` to run:

image

**Comment by icetianli** [comment]
Thanks all, will sort this notebook out asap.

**Pull request merged**
