### PR TITLE
Looking at plotting mesh on map

### LINKED ISSUE #135: hydro tutorial should use new mesh mapper
Currently the hydro tutorial uses the built in plotting function to plot the mesh like so:

image

However we should have it use the more useful fdmr tools to map it like it does in the meshbuilder app.

### PR DESCRIPTION
**Pull request by gareth-j**
* **Summary of changes** (Bug fix, feature, docs update, ...)

Looking at plotting a mesh on a leaflet map. Needs some work due to CRS issues.

* **Please check if the PR fulfills these requirements**

- [x] Closes #135 
- [x] Vignettes updated/added
- [x] Added an entry in the latest `CHANGELOG.md` file if fixing a bug or adding a new feature

### CODE REVIEW

**Review by mnky9800n — APPROVED** [review]
this replaces the mesh plotting in the hydro tutorial with the mesh shiny app.

**Comment by mnky9800n** [comment]
@gareth-j for some reason it is cancelingg the checks for macos and ubuntu. can you tel lme why?

**Comment by gareth-j** [comment]
Hmm no that's weird. This PR isn't really ready to go anywhere though. We need to decide what we expect the user to pass in.

**Review by XueqingYin — APPROVED** [review]
Thanks, nice mesh plotting.

**Comment by XueqingYin** [comment]
When I ran the function, I got a warning that read: "In inla.not_for_PROJ6("inla.CRSargs") : 'inla.CRSargs' should not be used with PROJ6. Call stack for developer debugging..." (as shown in the attached picture). I don't quite understand this warning, and it does not seem to affect the mesh plotting, but is it possible to prevent it from being printed out?

plot_mesh_warnings

**Comment by gareth-j** [comment]
> When I ran the function, I got a warning that read: "In inla.not_for_PROJ6("inla.CRSargs") : 'inla.CRSargs' should not be used with PROJ6. Call stack for developer debugging..." (as shown in the attached picture). I don't quite understand this warning, and it does not seem to affect the mesh plotting, but is it possible to prevent it from being printed out?
> 
> plot_mesh_warnings

@XueqingYin I've removed the code that calls the `inla.CRSargs` function, does that stop those warnings from showing up?

**Review by XueqingYin — APPROVED** [review]
Yes, it stops printing these warnings. Thanks @gareth-j !

**Pull request merged**
