### PR TITLE
3. Add better checks and default CRS to `mesh_builder`

### LINKED ISSUE #146: mesh_builder should guess a projection if the user doesnt provide one
Currently the meshbuiilder app will give the following error if your dataframe doesnt have a projection:

```
Error in spatial_data@data :
no applicable method for `@` applied to an object of class "data.frame"
5.
c("LONG", "LAT") %in% names(spatial_data@data) at shiny_meshbuilder.R#61
4.
meshbuilder_shiny(spatial_data = spatial_data, obs_data = obs_data,
crs = crs, max_edge = max_edge, offset = offset, cutoff = cutoff)
3.
as.shiny.appobj(appDir)
2.
shiny::runApp(meshbuilder_shiny(spatial_data = spatial_data,
obs_data = obs_data, crs = crs, max_edge = max_edge, offset = offset,
cutoff = cutoff)) at shiny_meshbuilder.R#248
1.
fdmr::mesh_builder(data)
```

This is because there is no projection. However we can fix this by providing a projection by having a default proj4 string.

We should also give the user a warning saying it is using the default proj4 string and the locations may be offset.

### PR DESCRIPTION
**Pull request by gareth-j**
> **_NOTE:_**  #147 and #158 should go in before this PR.

* **Summary of changes** (Bug fix, feature, docs update, ...)

This fixes some small issues with the meshbuilder tool

* **Please check if the PR fulfills these requirements**

- [x] Closes #146 
- [ ] Tests added and passed
- [ ] All code checks passing - `styler` run over code
- [ ] Vignettes updated/added
- [x] Added an entry in the latest `CHANGELOG.md` file if fixing a bug or adding a new feature
- [ ] Any new libraries added to `DESCRIPTION`

### CODE REVIEW

**Review by XueqingYin — COMMENTED** [review]
The mesh builder looks good to me, thanks @gareth-j . But I found two issues related to the priors shiny app and the model_viewer shinp app. They also exist in PRs #158 , #163 , which are 

(a) the wrong argument name was used when calling the ```create_prediction_field``` function within the function```model_viewer_shiny()``` in shiny_modelviewer.R. It should be ``` create_prediction_field (…, data_dist = data_type ,…)```, rather than ```create_prediction_field (…, data_type = data_type ,…)``` 

(b) we should use the following codes in shiny_priors.R to check and set the default CRS if it’s not given, otherwise the prior app returns: “Error in if (is.na(mesh_crs)) { : argument is of length zero” 
```
if ( (is.null(mesh_crs) || is.na(mesh_crs)) && (is.na(spatial_crs) || is.null(spatial_crs)) ) {
  warning("Cannot read CRS from mesh or spatial_data, using default CRS = +proj=longlat +datum=WGS84")
  crs <- "+proj=longlat +datum=WGS84"
} else if (is.na(mesh_crs) || is.null(mesh_crs) ) {
  crs <- spatial_crs
} else {
  crs <- mesh_crs
}

```

**Comment by gareth-j** [comment]
> The mesh builder looks good to me, thanks @gareth-j . But I found two issues related to the priors shiny app and the model_viewer shinp app. They also exist in PRs #158 , #163 , which are
> 
> (a) the wrong argument name was used when calling the `create_prediction_field` function within the function`model_viewer_shiny()` in shiny_modelviewer.R. It should be ` create_prediction_field (…, data_dist = data_type ,…)`, rather than `create_prediction_field (…, data_type = data_type ,…)`
> 
> (b) we should use the following codes in shiny_priors.R to check and set the default CRS if it’s not given, otherwise the prior app returns: “Error in if (is.na(mesh_crs)) { : argument is of length zero”
> 
> ```
> if ( (is.null(mesh_crs) || is.na(mesh_crs)) && (is.na(spatial_crs) || is.null(spatial_crs)) ) {
>   warning("Cannot read CRS from mesh or spatial_data, using default CRS = +proj=longlat +datum=WGS84")
>   crs <- "+proj=longlat +datum=WGS84"
> } else if (is.na(mesh_crs) || is.null(mesh_crs) ) {
>   crs <- spatial_crs
> } else {
>   crs <- mesh_crs
> }
> ```

OK these issues should be fixed now.

**Review by mnky9800n — APPROVED** [review]
this makes it so mesh builder assumes wgs84 if no projection is specified by the user. previously the app would fail if you didn't provide a proj4 string.

**Comment by XueqingYin** [comment]
All good now

**Pull request merged**
