### PR TITLE
Ensure we can write logfiles or fail graciously

### LINKED ISSUE #97: Writable log file issue
Xueqing encountered an error when the Priors app tried writing out to file. We should add some checks to make sure this doesn't crash the app.

### PR DESCRIPTION
**Pull request by gareth-j**
* **Summary of changes** (Bug fix, feature, docs update, ...)

This makes sure we can either write out logfiles somewhere, either to `~/fdmr/logs`, `$TMPDIR` or not at all.

* **Please check if the PR fulfills these requirements**

- [x] Closes #97 
- [x] Tests added and passed
- [ ] All code checks passing - `styler` run over code
- [ ] Vignettes updated/added
- [ ] Added an entry in the latest `CHANGELOG.md` file if fixing a bug or adding a new feature
- [ ] Any new libraries added to `DESCRIPTION`

### CODE REVIEW

**Review by XueqingYin — CHANGES_REQUESTED** [review]
Thanks @gareth-j . I’ve tested it, but got the warnings shown in pic1.jpg and pic2.jpg. 

I think the warning in pic1.jpg is because in shiny_priors.R the first argument names “logfile” in both write_parameters() and write_log() haven’t been updated to “filepath”

The warnings in pic2.jpg appear to be related to a file writing issue. Not sure if this is affecting only me or if john encounters the same problem.
pic1

pic2

Xueqing

**Comment by gareth-j** [comment]
Thanks for finding those issues @XueqingYin, I've just made a few changes. You can now pass in a `log_folder` argument so you can make sure the logs can be written. I've also added some extra error handling so the app shouldn't crash if we can't write out. You might see some warnings but these should just be informative.

**Comment by XueqingYin** [comment]
Thanks @gareth-j . If I don’t pass in the log_folder argument, it returns following error: 
pic3

I guess this is because in the function priors_shiny(…), we need to use “if (is.null(log_folder) ) { } “ to determine if log_folder is NULL rather than if (log_folder == NULL) { … }. 

When I pass in a log_folder argument, it still cannot write out and gives warnings similar to the previous ones, however it doesn’t crash anymore, and the app output looks normally. Do you think this log writing issue is only specific to my computer setting, and not a general problem? 

Xueqing

**Comment by gareth-j** [comment]
> Thanks @gareth-j . If I don’t pass in the log_folder argument, it returns following error: pic3
> 
> I guess this is because in the function priors_shiny(…), we need to use “if (is.null(log_folder) ) { } “ to determine if log_folder is NULL rather than if (log_folder == NULL) { … }.
> 
> When I pass in a log_folder argument, it still cannot write out and gives warnings similar to the previous ones, however it doesn’t crash anymore, and the app output looks normally. Do you think this log writing issue is only specific to my computer setting, and not a general problem?
> 
> Xueqing

It looks like it might be a Windows issue not letting you write to those folders. Can you create a directory in your home folder and see if you can write the logs to that?

**Review by XueqingYin — APPROVED** [review]
Thanks @gareth-j . It still cannot write out, but John doesn't seem to have the same problem, so it might not be a major issue. Xueqing.

**Comment by gareth-j** [comment]
> Thanks @gareth-j . It still cannot write out, but John doesn't seem to have the same problem, so it might not be a major issue. Xueqing.

OK I think this must be a Windows issue. I'll have a look into it.

**Comment by gareth-j** [comment]
I'll merge this so we can have more stable log writing on other platforms. See #104 for Windows.

**Pull request merged**
