### PR TITLE
Adding tooltips to Shiny apps

### LINKED ISSUE #187: Hover tooltip for priors app
It'd be nice to have hover tooltips on the priors app. Or if that isn't possible then an expandable piece of text would be good.

### PR DESCRIPTION
**Pull request by gareth-j**
* **Summary of changes** (Bug fix, feature, docs update, ...)

This will add tooltips to the shiny apps using the [`bslib`](https://rstudio.github.io/bslib/index.html) package.

* **Please check if the PR fulfills these requirements**

- [x] Closes #187 
- [ ] Tests added and passed
- [x] All code checks passing - `styler` run over code
- [ ] Vignettes updated/added
- [ ] Added an entry in the latest `CHANGELOG.md` file if fixing a bug or adding a new feature
- [ ] Any new libraries added to `DESCRIPTION`

### CODE REVIEW

**Comment by gareth-j** [comment]
@XueqingYin could you add some useful text to the tooltip strings in `shiny_modelbuilder.R` from line 111?
There's one for each prior.

Also what do you think of the new layout? It seemed a waste of space to have the priors in the sidebar constantly.

@mnky9800n what are your thoughts?

**Comment by XueqingYin** [comment]
Thanks @gareth-j . I have pulled a request #221  to add text to the tooltips. I prefer the new layout, and I think it would be better if we also include a label 'Spatial priors' above ```range0``` and ```Prange``` , and 'Field priors' above ```sigma0``` and ```Psigma```. Currently, there is only one label, 'Temporal priors', for ```prior_alpha``` and ```pg_alpha```. 

image

**Comment by gareth-j** [comment]
I've just added those headers @XueqingYin, does that look better?

**Comment by XueqingYin** [comment]
Thanks @gareth-j , it looks great.  Just one issue, the tooltips or text doesn't pop up when I hover the mouse over the parameters. 

image

**Comment by gareth-j** [comment]
> Thanks @gareth-j , it looks great. Just one issue, the tooltips or text doesn't pop up when I hover the mouse over the parameters.
> 
> image

That's really weird. Did they work before? Are there any error messages in the console?

**Comment by XueqingYin** [comment]
They didn't work before either, and no errors in the console. However, I just found that the tips only display when opening the Shiny App in the web Browser, but they don't work in the inbuilt browser within R-Studio.

image

**Comment by gareth-j** [comment]
OK cool, I'll add a note to the documentation to tell users that.

**Pull request merged**
