### PR TITLE
1. Priors Shiny App

### LINKED ISSUE #46: Add Remotes section to Description
As per Rita's suggestion we should add INLA as a remote dependency to the Description file.

```
Remotes: hrue/r-inla/tree/stable 
```

### LINKED ISSUE #54: priors + modeling shiny app
As discussed in the milestone meeting, we need a way to visualize priors and model impacts on the predictive ability of the model.

In the below diagram i have sketched out a shiny app interface that will let us do that.

* at the top there is a slider bar to change the prior value for the spatial wavelength of the prior
* below is a list of features based on the input data column headers that can be used to construct the fit equation
* below the list of features is the constructed equation
* to the right is the visualization. in this case i assume that the visualization should be the collected outcome variable (y) that has been histogrammed in some way that is agnostic to the data. Then a kernel density estimate of the model predicted variables (that is, basically, a continuous histogram) is plotted on top to show the model.
* There could also be "run model" button at the bottom to match the mesh builder app, that way it doesn't need to auto update

image

### LINKED ISSUE #70: Add 4DModeller loading GIF
Add Richard's 4DModeller loading GIF to Shiny apps.

### LINKED ISSUE #76: Shiny app - logging?
Would logging model output and prior sets to file be helpful?

### PR DESCRIPTION
**Pull request by gareth-j**
This will add a new Shiny app for testing of different priors.

### Interface
- [x] Store the result of each run to allow easy comparison graphically.
- [x] Add building SPDE section to vignette
- [x] Slider for modifying other priors

### Plotting
- [x] Boxplot
- [x] AR(1)
- [x] Density
- [x] DIC

### Export
- [x] Code
- [x] Priors
- [ ] Plots?

### Other

- [ ] Tidy model output text
- [ ] Add regex to do some checks on the string we're evaluating
- [ ] Can we pipe the terminal output to the Shiny app? - low priority
- [x] Check for coordinates LAT LONG being set on data

Closes #54 
Closes #70 
Closes #46 
Closes #76

### CODE REVIEW

**Review by XueqingYin — COMMENTED** [review]
Hi @gareth-j , 

Thanks for the work. I’ve reviewed the vignette and the model running process and basic output look good to me.  There are just two minor points to be noted.

1.	The vignette is missing a step for building SPDE model and then specifying priors for spatial range parameter and marginal standard deviation parameter, which is:

spde <- INLA::inla.spde2.pcmatern(
  mesh = mesh,
  prior.range = c(prior_spatial_range, prior_range_probability),
  prior.sigma = c(prior_standard_deviation, prior_sd_probability)
)
The priors are specified by changing the values of “prior_spatial_range, prior_range_probability, prior_standard_deviation and prior_sd_probability” based on users’ knowledge, so there should be slider bars to change their values on the Prior ShinyApp. In addition, slide bars should also be included for the prior values of the temporal correlation parameter. The prior for temporal correlation parameter is specified by changing the values of “prior_alpha”, “pg_alpha” in the code below.
rhoprior <- list(theta = list(prior = "pccor1", param = c(prior_alpha, pg_alpha)))

2.	The vignette uses the Bristol COVID-19 data by directly filtering the entire COVID-19 data within Bristol. An issue of that is the temporal index does not start from 1 and is not continuous, which is not expected by INLA. So the time index needs to be reorganized into the correct format in the final version. 

I’ve been working on space-time MCMC this week. Next week I will focus on the prior tutorial and preparing a Bristol dataset set that contains the expected time index, the response variable, and the selected covariates. The tutorial will explain the data, the priors, then run BHM based on different prior values, and finally compare the model outputs by plotting histograms / density curves. 

Xueqing

**Comment by gareth-j** [comment]
It'd be nice to be able to compare the results of different priors.
Store the result of each run to allow easy comparison graphically.

**Comment by gareth-j** [comment]
How do we want to go about defining the group index and the number of groups? At the moment they're hard coded.

```
group_index <- measurement_data$week
n_groups <- length(unique(measurement_data$week))
```

**Review by aabelean — APPROVED** [review]
Seconding Xueqing's suggestion

**Review by XueqingYin — APPROVED** [review]
Thank you @gareth-j . A minor suggestion on the text for temporal priors help in shiny_priors.R. I was wondering if you could replace the current symbol "a" with the symbol "α" 
when referring to temporal autocorrelation parameter in the text, as "α" would align better with  "alpha". Apart from this, all look good to me.

Xueqing

**Comment by gareth-j** [comment]
> Thank you @gareth-j . A minor suggestion on the text for temporal priors help in shiny_priors.R. I was wondering if you could replace the current symbol "a" with the symbol "α" when referring to temporal autocorrelation parameter in the text, as "α" would align better with "alpha". Apart from this, all look good to me.
> 
> Xueqing

OK great, thanks! I've made those changes now.

**Pull request merged**
